root_dir: ${oc.env:PROJECT_ROOT}/data-release
structure:
  init: "from_cif"          # or "from_cif" or pymatgen
  n_atoms: 500
  box_length: 25.0 #Trying a smaller box to see if that helps
  species: [Ge, O]
  stoichiometry: [167, 333]
  cif_path: ${data.root_dir}/crystal-structures/c-GeO2.cif
  target_density: 2.20