root_dir: ${oc.env:PROJECT_ROOT}/data-release

structure:
  init: "from_cif"
  species: [Fe, O]          # Elements present
  stoichiometry: [108, 162]     # Fe2O3 ratio
  cif_path: ${data.root_dir}/crystal-structures/Fe2O3.cif

  target_density: 5.15
