root_dir: ${oc.env:PROJECT_ROOT}/data-release

structure:
  init: "from_cif" #or random_icp depending on how you want your initial configuration to be
  n_atoms: 992                    # Total atoms from your defected structure
  box_length: 21.78              # From your γ-Li3PO4 supercell (2×2×2)
  species: [Li, P, O, N]          # Four element types
  stoichiometry: [376, 128, 448, 40]
                                  # Ratio: Li2.94PO3.50N0.31 per P
  cif_path: ${data.root_dir}/crystal-structures/LiPON_defected.cif
  target_density: 2.30            # g/cm³ - typical for LiPON thin films