#root_dir: ${oc.env:PROJECT_ROOT}/data-release
#
#structure:
#  init: "from_cif"
#  n_atoms: 1375
#  box_length: 25.0
#  species: [P, S]
#  stoichiometry: [324, 1051]  # 3:1:1 ratio for Li3PS4
#  cif_path: ${data.root_dir}/crystal-structures/glass_67Li2S.cif
#  target_density: 2.37  # Approximate density for Li3PS4

root_dir: ${oc.env:PROJECT_ROOT}/data-release

structure:
  init: "from_cif"
  n_atoms: 11495
  box_length: 25.0
  species: [P, S]
  stoichiometry: [2592, 8093]  # 3:1:1 ratio for Li3PS4
  cif_path: ${data.root_dir}/crystal-structures/glass_67Li2S.cif
  target_density: 2.37  # Approximate density for Li3PS4