root_dir: ${oc.env:PROJECT_ROOT}/data-release

structure:
  init: "from_cif"
  n_atoms: 256
  box_length: 39.6
  species: [Na, Ta, Cl]
  stoichiometry: [0, 288, 1728]
  cif_path: ${data.root_dir}/crystal-structures/NaTaCl6.cif
  target_density: 2.94
