root_dir: ${oc.env:PROJECT_ROOT}/data-release
structure:
  init: "from_cif"          # or "from_cif" or pymatgen
  n_atoms: 1125
  box_length: 25.0 #Trying a smaller box to see if that helps
  species: [Si, O]
  stoichiometry: [375, 750]
  cif_path: ${data.root_dir}/crystal-structures/c-SiO2.cif
  target_density: 2.20        # used only in `from_cif` mode

